root: true
extends:
  - "@joshuaavalon/eslint-config-typescript"
  - "next/core-web-vitals"
env:
  es6: true
  node: true
rules:
  "@typescript-eslint/naming-convention":
    - error
    - selector: variable
      modifiers:
        - destructured
      format: null
